# Generated by Django 3.2.8 on 2021-11-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='post_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
