# Generated by Django 3.2.8 on 2021-11-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
