# Generated by Django 3.2.6 on 2021-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_companyprofile_jobs_jobseekerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'jobseeker'), ('employer', 'employer')], default='employer', max_length=20),
        ),
    ]
