# Generated by Django 3.2.8 on 2021-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobseekerprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='photo',
            field=models.ImageField(upload_to='image'),
        ),
    ]
